security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        parents:
            entity: { class: App\Entity\Parents, property: parents_pseudo}
        entreprises:
            entity: { class: App\Entity\Entreprises, property: entreprises_pseudo}


    firewalls:
        parents:
            pattern: ^/
            anonymous: true
            provider: parents
            guard:
                authenticators:
                    - App\Security\ConnexionFormAuthenticator
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: app_logout
        entreprises:
            pattern: ^/
            anonymous: true
            provider: entreprises
            guard:
                authenticators:
                    - App\Security\LoginEntrFormAuthenticator
            form_login:
                login_path: /loginentr
                check_path: /loginentr
            logout:
                path: app_logoutentr
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
    encoders:
        App\Entity\Parents: bcrypt
        App\Entity\Entreprises: bcrypt

