easy_admin:
  design:
      brand_color: '#1ABC9C'
      menu:
        - label: 'Utilisateurs'
          children:
            - { entity: 'Parents', icon: 'user' }
            - { entity: 'Enfants', icon: 'user' }

