easy_admin:
  entities:
    Entreprises:
      disabled_actions: ['new']
      class: App\Entity\Entreprises
      label: 'Entreprises'
      list:
        title: 'Entreprises'
        fields:
          - 'id'
          - { property: 'entreprises_mail', type: 'email', label: 'Email' }
          - { property: 'entreprises_nom', type: 'string', label: 'Nom' }
          - { property: 'entreprises_role', type: 'simple_array', label: 'Rôle' }
          - { property: 'entreprises_telephone', type: 'string', label: 'Téléphone' }
          - { property: 'entreprises_siret', type: 'integer', label: 'Numéro de Siret' }
          - { property: 'entreprises_note', type: 'float', label: 'Note' }
          - { property: 'entreprises_status', type: 'toggle', label: 'Status' }
          - { property: 'entreprises_date_creation', type: 'datetime', label: 'Date de création' }
          - { property: 'entreprises_date_modif', type: 'datetime', label: 'Date de modification' }
          - { property: 'Entreprises_Bracelet', type: 'simple_array', label: 'Bracelets ID' }
      edit:
        title: 'Modification Entreprises'
        fields:
          - { property: 'entreprises_status', label: 'Status' , type: 'checkbox' , css_class: 'form-widget'}
          - { property: 'entreprises_date_modif', label: 'Date de modification' , type: 'date'}

